"""empty message

Revision ID: a0466944990c
Revises: None
Create Date: 2016-06-09 21:54:09.208693

"""

# revision identifiers, used by Alembic.
revision = 'a0466944990c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lunch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=63), nullable=True),
    sa.Column('food', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lunch')
    ### end Alembic commands ###
